### PR TITLE
Update build and test

### PR DESCRIPTION
**Pull request by bollwyvl**
Thanks for this package! 

I went ahead and added it to [`conda-forge`](https://github.com/conda-forge/pep440-feedstock) to support testing `nbformat`, and noticed some relatively quick packaging/testing wins. Happy to roll back any of these that are displeasing for compatibility/complexity reasons.

## Chore Changes
- [x] update `pyproject.toml` to flit with PEP621 metadata
- [x] capture some test deps
- [x] remove travis, add github actions (see [self-PR](https://github.com/bollwyvl/pep440/pull/1/checks))
- [x] get up to 100% test coverage
- [x] lint with mypy 

## Code Changes
- [x] normalize return codes for CLI (`-1` -> `255` on unix _or_ `BIGASSNUMBER` on win32)

### CODE REVIEW

**Comment by bollwyvl** [comment]
:rofl:

**Comment by Carreau** [comment]
Released.

**Comment by Carreau** [comment]
Happy to also move it to an org if you think it's a good idea. I had forgotten this package....

**Comment by bollwyvl** [comment]
Yeah, it's a little odd to me that any PEP that _could_ have a package doesn't basically require having a pure-python reference implementation in a top-level org... but i don't think it's worth hustling too hard.

**Pull request merged**
